pyap/blog/urls.py
from django.conf.urls import url

from .views import BlogDetailView, BlogListView  #, LatestEntriesFeed

urlpatterns = [
    url(r'^(?P<slug>[-_\w]+)/$', BlogListView.as_view(), name='blog_index'),
    url(r'^(?P<blog_slug>[-_\w]+)/(?P<post_slug>[-_\w]+)/$',
        # r'^(?P<blog_slug>[-_\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$',
        BlogDetailView.as_view(),
        name='blog_detail',
        ),
    # url(r'^archive/$',
    #     BlogListView.as_view(
    #         template_name="blog/post_archive.html"),
    #         # page_template="blog/post_archive_page.html"),
    #         name="blog_archive"),
    # url(r'^latest/feed/$', LatestEntriesFeed()),
]

pyap/cointrax/urls.py
from django.conf.urls import include, url

from cointrax import views


urlpatterns = [
    url(r'^captcha/', include('captcha.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^address/(\S+)/$', views.address, name='address'),
    url(r'^not-available/$', views.not_available, name='not_available'),
    url(r'^not-in-system/$', views.not_in_system, name='not_in_system'),
    url(r'^forbidden/$', views.forbidden, name='forbidden'),
    url(r'^btcprice/', views.btcprice, name='btcprice'),
    url(r'^btctrans/(\S+)/', views.btctrans, name='btctrans'),
    url(r'^qrcode/', views.qrcode, name='qrcode'),
    url(r'^address-report/', views.address_report, name='address_report'),
    url(r'^registration-report/', views.registration_report, name='registration_report'),
]

pyap/pyap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site as filebrowser_site
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from seo.init import sitemaps
from seo.views import robots_txt


urlpatterns = [
    url(r'^admin/filebrowser/', include(filebrowser_site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/password_reset/$', auth_views.password_reset, name='admin_password_reset'),
    url(r'^admin/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^', include('home.urls', namespace='home')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^page/', include('page.urls', namespace='page')),
    # url(r'^review/', include('review.urls', namespace='review')),

    url(r'^blog/', include('blog.urls')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),

    url(r'^cointrax/', include('cointrax.urls')),

    # modules
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^cart/', include('cart.urls', namespace='cart')),

    url(r'^sitemap\.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt', robots_txt, name='robots_txt'),
    # ---- Приоритет имеет значение! ----
    url(r'^catalog/', include('catalog.urls', namespace='catalog')),

    url(r'^', include('product.urls', namespace='product')),
    url(r'^', include('settings_template.urls')),
    url(r'^dev_init/', include('dev_init.urls')),

    # url(r'^(?P<url>[_\-\w\d]+)/$', url_hendler, name='url_handler'),
    # url(r'^defauldb/(?P<app>[_\-\w\d]+)/$', AddDefaultDB.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
                   + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pyap/cointrax/models.py
from django.db import models
from django import forms

from captcha.fields import CaptchaField


class PaymentAddress(models.Model):
    btc_address = models.CharField(max_length=35)
    available = models.BooleanField(default=True)


class Registration(models.Model):
    full_name = models.CharField(max_length=100)
    email_address = models.CharField(max_length=254)
    btc_price = models.DecimalField(max_digits=8, decimal_places=2)
    payment_usd = models.DecimalField(max_digits=5, decimal_places=2)
    payment_btc = models.IntegerField()
    btc_address = models.CharField(max_length=35)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)


class RegistrationForm(forms.Form):
    full_name = forms.CharField(
        label='Name', max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Full name'})
    )
    email_address = forms.EmailField(label='Email address', max_length=254)
    captcha = CaptchaField(label='')
    btc_price = forms.DecimalField(max_digits=8, decimal_places=2,
                                   widget=forms.HiddenInput())
    payment_usd = forms.DecimalField(
        label='Payment (USD)', min_value=0, max_digits=5, decimal_places=2,
        widget=forms.TextInput(attrs={'placeholder': 'Dollars'})
    )

pyap/cointrax/views.py
import json
import tempfile
from decimal import Decimal
import logging

import pytz
import requests
import pyqrcode

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.core.urlresolvers import reverse
from django.template import Context, Template
from django.template.loader import get_template
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required, user_passes_test

from cointrax.models import PaymentAddress, Registration, RegistrationForm

logger = logging.getLogger(__name__)


class RegistrationInfo(object):
    def __init__(self):
        self.date_added = None
        self.full_name = ''
        self.email_address = ''
        self.payment_usd = 0
        self.payment_mbtc = 0
        self.received_mbtc = 0
        self.btc_price = 0
        self.btc_address = ''
        self.paid = False

    def get_payment_usd_str(self):
        return '%.2f' % self.payment_usd

    def get_payment_mbtc_str(self):
        return '%.5f' % self.payment_mbtc

    def get_received_mbtc_str(self):
        return '%.5f' % self.received_mbtc

    def get_btc_price_str(self):
        return '%.2f' % self.btc_price


def in_managers_group(user):
    """
    Returns True if the user is in the managers group.
    """
    return user.groups.filter(name='managers').exists()


def index(request):
    if request.method == 'POST':
        # This is a POST request so we need to process the form data.
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # Process the form data.
            full_name = form.cleaned_data['full_name']
            email_address = form.cleaned_data['email_address']
            payment_usd = form.cleaned_data['payment_usd']
            btc_price = form.cleaned_data['btc_price']

            # Get the next available payment address.
            try:
                address_set = PaymentAddress.objects.filter(available=True)
            except Exception as e:
                logger.error('Unable to query PaymentAddress table: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})

            if len(address_set) == 0:
                return HttpResponseRedirect(reverse('not_available'))
            payment_address = address_set[0]

            # Mark this payment address as not available.
            try:
                payment_address.available = False
                payment_address.save()
                logger.info('Reserving BTC address %s' %
                            payment_address.btc_address)
            except Exception as e:
                logger.error('Unable to update PaymentAddress table: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})

            # Create a Registration record.
            registration = Registration()
            registration.full_name = full_name
            registration.email_address = email_address
            registration.payment_usd = payment_usd
            registration.btc_price = btc_price

            # Calculate BTC payment and and store in Satoshis.
            registration.payment_btc = int(payment_usd/btc_price *
                                           100000000)

            registration.btc_address = payment_address.btc_address
            try:
                registration.save()
                logger.info('Created registration record for %s' %
                            registration.full_name)
            except Exception as e:
                logger.error('Unable to update Registration table: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})

            # Calculate the payment in BTC and mBTC.
            payment_btc = (Decimal(registration.payment_btc) / 100000000).quantize(Decimal('0.00000001'))
            payment_mbtc = (Decimal(registration.payment_btc) / 100000).quantize(Decimal('0.00001'))

            # Create context object for emails.
            c = Context({'registration': registration,
                         'payment_btc': payment_btc,
                         'payment_mbtc': payment_mbtc,
                         'event_name': settings.EVENT_NAME,
                         'hosturl': settings.HOSTURL})

            # Send an email to the registrant.
            reg_text_t = get_template('registrant_email.txt')
            reg_html_t = get_template('registrant_email.html')
            reg_text = reg_text_t.render(c)
            reg_html = reg_html_t.render(c)
            subject = '%s Bitcoin Registration' % settings.EVENT_NAME
            if settings.ENVIRONMENT_NAME:
                subject += ' - %s' % settings.ENVIRONMENT_NAME
            try:
                send_mail(subject, reg_text, 'webmaster@goldmoth.com',
                          [registration.email_address], html_message=reg_html)
                logger.info(
                    'Sent registration email to %s (%s)' %
                    (registration.full_name, registration.email_address)
                )
            except Exception as e:
                logger.error('Error sending email: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})

            # Send an email to each manager.
            notification_list = []
            try:
                managers_group = Group.objects.get(name='managers')
            except Exception as e:
                logger.error('Unable to query for managers: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})
            managers = managers_group.user_set.all()
            for manager in managers:
                notification_list.append(manager.email)
            mgr_text_t = get_template('manager_email.txt')
            mgr_html_t = get_template('manager_email.html')
            mgr_text = mgr_text_t.render(c)
            mgr_html = mgr_html_t.render(c)
            subject = '%s Bitcoin Registration (%s)' % (registration.full_name,
                                                        settings.EVENT_NAME)
            if settings.ENVIRONMENT_NAME:
                subject += ' - %s' % settings.ENVIRONMENT_NAME
            try:
                send_mail(subject, mgr_text, 'webmaster@goldmoth.com',
                          notification_list, html_message=mgr_html)
                logger.info(
                    'Sent emails to managers regarding registration '
                    'for %s (%s)' %
                    (registration.full_name, registration.email_address)
                )
            except Exception as e:
                logger.error('Error sending email: %s' % e)
                return render(request, '500.html',
                              {'event_name': settings.EVENT_NAME,
                               'environment_name': settings.ENVIRONMENT_NAME})

            # Redirect to the payment page.
            return HttpResponseRedirect(
                reverse('address', args=([payment_address.btc_address]))
            )
    else:
        # Make sure we have an available bitcoin address for the registrant.
        try:
            address_set = PaymentAddress.objects.filter(available=True)
        except Exception as e:
            logger.error('Unable to query PaymentAddress table: %s' % e)
            return render(request, '500.html',
                          {'event_name': settings.EVENT_NAME,
                           'environment_name': settings.ENVIRONMENT_NAME})
        if len(address_set) == 0:
            return HttpResponseRedirect(reverse('not_available'))

        # Create a blank form.
        form = RegistrationForm()

    return render(request, 'index.html',
                  {'form': form,
                   'event_name': settings.EVENT_NAME,
                   'environment_name': settings.ENVIRONMENT_NAME})


def btcprice(request):
    results = {}
    results['timestamp'] = timezone.localtime(timezone.now()).strftime('%m/%d/%Y %H:%M:%S %Z')
    try:
        r = requests.get('https://blockchain.info/ticker', timeout=10.0)
    except requests.exceptions.Timeout:
        logger.error('Timeout querying for BTC price')
        results['successful'] = False
        results['price'] = 0
    except requests.exceptions.RequestException as e:
        logger.error('Error querying for BTC price: %s' % e)
        results['successful'] = False
        results['price'] = 0
    else:
        if r.status_code == 200:
            results['successful'] = True
            results['price'] = r.json()['USD']['last']
        else:
            logger.error(
                'Received status code %d when querying for BTC price' %
                r.status_code
            )
            results['successful'] = False
            results['price'] = 0
    json_data = json.dumps(results)
    return HttpResponse(json_data, content_type='application/json')


def address(request, btc_address):
    # Make sure the registration record exists.
    try:
        queryset = Registration.objects.filter(btc_address=btc_address)
    except Exception as e:
        logger.error('Unable to query PaymentAddress table: %s' % e)
        return render(request, '500.html',

pyap/cointrax/templates/address.html
{% extends "base.html" %}

{% block content %}
<div class="row">
  <div class="col-md-6">
    <h3>Bitcoin Payment</h3>

    <p>Please make your payment of {{ payment_btc }} BTC
    ({{ payment_mbtc }} mBTC) to this address:</p>

    <p><strong>{{ registration.btc_address }}</strong></p>

    <img class="qrcode" src="{% url 'qrcode' %}?address={{ registration.btc_address }}&label=MPLC&amount={{ payment_btc }}">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Transactions</h3>
      </div>
      <div class="panel-body">
        <div id="btc_transactions">Checking for transactions ...</div>
        <div id="btc_timestamp">&nbsp;</div>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <h3>Registration Details</h3>

    <table class="table table-bordered">
      <tr>
        <td><strong>Name</strong></td>
        <td>{{ registration.full_name }}</td>
      </tr>
      <tr>
        <td><strong>Email address</strong></td>
        <td><a href="mailto:{{ registration.email_address }}">{{ registration.email_address }}</a></td>
      </tr>
      <tr>
        <td><strong>Payment (USD)</strong></td>
        <td>{{ registration.payment_usd|floatformat:2 }}</td>
      </tr>
      <tr>
        <td><strong>Payment (mBTC)</strong></td>
        <td>{{ payment_mbtc }}</td>
      </tr>
      <tr>
        <td><strong>BTC price at time of registration</strong></td>
        <td>1 BTC = {{ registration.btc_price }} USD</td>
      </tr>
      <tr>
        <td><strong>Registration date</strong></td>
        <td>{{ registration.date_added|date:"m/d/Y H:i" }}</td>
      </tr>
    </table>

    <p>You can bookmark this page for future reference.</p>

    {% include "contact.html" %}
  </div>
</div>
{% endblock %}

{% block pagescripts %}
<script>
  // Periodically query for transaction history.
  var delay = 10000;
  (function worker() {
    $.ajax({
      url: "{% url 'btctrans' registration.btc_address %}",
      success: function(data) {
        if (data.successful) {
          var index;
          trans_html = '';
          if (data.transactions.length === 0) {
            trans_html = 'No transactions received.';
          }
          else {
            for (index = 0; index < data.transactions.length; ++index) {
              trans_html += 'Received ' + data.transactions[index][0] + ' mBTC (' + data.transactions[index][1] + ')<br \\>';
            }
            trans_html += 'Total: ' + data.total_received + ' mBTC';
            delay = 60000;
          }
          $('#btc_transactions').html(trans_html);
          $('#btc_timestamp').html('Last updated: ' + data.timestamp);
        }
      },
      complete: function() {
        // Schedule the next request when the current one's complete.
        setTimeout(worker, delay);
      }
    });
  })();
</script>
{% endblock %}

pyap/cointrax/templates/address_report.html
{% extends "base.html" %}

{% block content %}
<h3>Available Addresses</h3>

{% if available_addresses.count == 1 %}
<p>There is one addresses available.</p>
{% else %}
<p>There are {{ available_addresses.count }} addresses available.</p>
{% endif %}

<p>
{% for address in available_addresses %}
{{ address.btc_address }}<br />
{% endfor %}
</p>
{% endblock %}

pyap/cointrax/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <title>{{ event_name }}</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
    {% block moremeta %}{% endblock %}
  </head>

  <body>
    <div class="container-fluid">
      <header>
        <h1>{{ event_name }}{% if environment_name %} - {{ environment_name }}{% endif %}</h1>
      </header>
      {% block content %}{% endblock %}
    </div>

    <script src="/static/js/jquery-1.11.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    {% block pagescripts %}{% endblock %}
  </body>
</html>

pyap/cointrax/templates/forbidden.html
{% extends "base.html" %}

{% block content %}
<h3>Forbidden</h3>

<p>You are not authorized to view this page. You may want to
<a href="/login/?next=/">login</a> and try again.</p>
{% endblock %}

pyap/cointrax/templates/index.html
{% extends "base.html" %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block content %}
<div class="row">
  <div class="col-md-7">
    <h3>Bitcoin Payment Form</h3>
    <p>Please enter your name below and the amount you are paying in USD.
    {% if event_name %}
    Please enter the same name you used on the {{ event_name}} registration
    form, so we can associate your payment with your registration.
    {% endif %}
    </p>

    <p>
    Click the <em>Calculate BTC</em> button at the bottom of the page to show the
    corresponding value in Bitcoin (BTC), based on the current exchange rate per
    <a href="https://markets.blockchain.info" target="_blank">blockchain.info</a>.
    Click <em>Next</em> and you will see a unique Bitcoin address to
    send your payment to, and you'll receive an email confirming your
    registration.</p>

    {% include "contact.html" %}

    <form action="{% url 'index' %}" method="post" role="form">
      {% csrf_token %}
      {% bootstrap_form_errors form type='non_fields' %}
      {% bootstrap_field form.full_name %}
      {% bootstrap_field form.email_address %}

      <div class="form-group form-horizontal">
        {{ form.captcha.errors }}
        <span><strong>Solve this problem:</strong> </span>
        <label class="control-label" for="{{ form.captcha.id_for_label }}"></label>
        {{ form.captcha }}
      </div>

      {% bootstrap_field form.btc_price %}
      {% bootstrap_field form.payment_usd %}
      <p id="payment_btc"><button id="calculate_btc" type="button" class="btn btn-default">Calculate BTC</button></p>
      <button type="submit" class="btn btn-primary">Next</button>
    </form>
  </div>
  <br />

  <div class="col-md-5">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Current Price</h3>
      </div>
      <div class="panel-body">
        <p id="btc_price">Retrieving price ...</p>
        <p id="btc_timestamp"></p>

        <p>Source:
        <a href="https://blockchain.info/ticker" target="_blank">blockchain.info</a>
        (JSON)</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block pagescripts %}
<script>
  var price = 0;

  $( document ).ready(function() {
    // Give focus to the full name field.
    $('#id_full_name').focus();

    // Calculate the BTC amount when the USD field changes.
    $('#id_payment_usd').change(function() {
      calc_btc();
    });

    // Calculate the BTC amount on Calculate or Re-calculate button click.
    $('#calculate_btc').click(function() {
      calc_btc();
    });
  });

  function calc_btc() {
    // Calculate the BTC amount and round it to 8 digits.
    payment_btc = $('#id_payment_usd').val() / price;
    payment_btc = Math.round(payment_btc * 100000000) / 100000000;

    // Calculate the mBTC amount.
    payment_mbtc = payment_btc * 1000;

    // Display the calculations along with a Re-calculate button.
    btc_html = '<strong>Payment (BTC):</strong> ' + payment_btc + ' BTC = ' +
               payment_mbtc + ' mBTC &nbsp' +
               '<button id="calculate_btc" type="button" class="btn btn-default">Re-calculate BTC</button>';
    $('#payment_btc').html(btc_html);
  }

  // Periodically query for the BTC price.
  (function worker() {
    $.ajax({
      url: "{% url 'btcprice' %}",
      success: function(data) {
        if (data.successful) {
          price = data.price;
          $('#btc_price').html('1 BTC = ' + data.price + ' USD');
          $('#btc_timestamp').html('Last updated: ' + data.timestamp);
          $('#id_btc_price').val(price);
          if ($('#id_payment_usd').val()) {
            calc_btc();
          }
        }
        else {
          $('#btc_price').html('Unable to retrieve Bitcoin price');
          $('#btc_timestamp').html('Last attempt: ' + data.timestamp + '.');
        }
      },
      error: function(data) {
        $('#btc_price').html('Unable to retrieve Bitcoin price');
        $('#btc_timestamp').html('Last attempt: ' + data.timestamp + '.');
      },
      complete: function() {
        // Schedule the next request when the current one's complete.
        setTimeout(worker, 30000);
      }
    });
  })();
</script>
{% endblock %}

pyap/cointrax/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-offset-2 col-md-10">
      <h3>Login</h3>

      {% if form.errors %}
        <p class="text-danger">Your username and password didn't match. Please try again.</p>
      {% endif %}
    </div>
  </div>

  <form method="post" action="{% url 'django.contrib.auth.views.login' %}"  class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_username" class="col-md-2 control-label">Username</label>
      <div class="col-md-10">
        <input type="text" class="form-control" id="id_username" name="username" placeholder="Username">
      </div>
    </div>
    <div class="form-group">
      <label for="id_password" class="col-md-2 control-label">Password</label>
      <div class="col-md-10">
        <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </div>
    <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}/{% endif %}" />
  </form>
{% endblock %}

{% block pagescripts %}
<script>
  $( document ).ready(function() {
    // Give focus to the username field.
    $('#id_username').focus();
  });
</script>
{% endblock %}

pyap/cointrax/templates/manager_email.html
<body>
<p><strong>{{ registration.full_name }}</strong> registered to pay with Bitcoin. Here are the
payment details:</p>

<table>
    <tr><td>Payment (USD):</td><td>${{ registration.payment_usd|floatformat:2 }}</td></tr>
    <tr><td>Payment (BTC):</td><td>{{ payment_btc }} BTC = {{ payment_mbtc }} mBTC</td></tr>
    <tr><td>BTC price at time of registration:</td><td>${{ registration.btc_price }}</td></tr>
    <tr><td>Registration date:</td><td>{{ registration.date_added|date:"m/d/Y H:i" }}</td></tr>
</table>

<p>Payment address: <strong>{{ registration.btc_address }}</strong></p>

<p>You can go to
<a href="{{ hosturl }}{% url 'address' registration.btc_address %}">{{ hosturl }}{% url 'address' registration.btc_address %}</a>
to see the status of this payment. You can go to
<a href="{{ hosturl }}{% url 'registration_report' %}">{{ hosturl }}{% url 'registration_report' %}</a>
to see the status of all registrations.</p>
</body>

pyap/cointrax/templates/not_available.html
{% extends "base.html" %}

{% block content %}
<h3>No Addresses Available for Payment</h3>

<p>Sorry, there are no bitcoin addresses available in the system at this time.</p>

{% include "contact.html" %}
{% endblock %}

pyap/cointrax/templates/not_in_system.html
{% extends "base.html" %}

{% block content %}
<h3>Error</h3>

<p>Sorry, that bitcoin addresses is not in the system.</p>
{% endblock %}

pyap/cointrax/templates/registrant_email.html
<body>
<p>{{ registration.full_name }},</p>

<p>Thanks for registering to pay in Bitcoin for the {{ event_name }}.
Here are your payment details:</p>

<table>
    <tr><td>Payment (USD):</td><td>${{ registration.payment_usd|floatformat:2 }}</td></tr>
    <tr><td>Payment (BTC):</td><td>{{ payment_btc }} BTC = {{ payment_mbtc }} mBTC</td></tr>
    <tr><td>BTC price at time of registration:</td><td>${{ registration.btc_price }}</td></tr>
    <tr><td>Registration date:</td><td>{{ registration.date_added|date:"m/d/Y H:i" }}</td></tr>
</table>

<p>If you have not done so, please make your payment to this address:</p>

<p><strong>{{ registration.btc_address }}</strong></p>

<p>You can also go to
<a href="{{ hosturl }}{% url 'address' registration.btc_address %}">{{ hosturl }}{% url 'address' registration.btc_address %}</a>
where you will see a QR code with this address.</p>

{% include "contact.html" %}

<p>Thank you.</p>
</body>

pyap/cointrax/templates/registration_report.html
{% extends "base.html" %}

{% block content %}
<h3>Registration Report <small>(newest to oldest)</small></h3>

{% if not registration_infos %}
  <p>No one has registered.</p>
{% else %}
  <table class="table table-responsive">
    <thead>
      <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Email Address</th>
        <th>USD</th>
        <th>mBTC</th>
        <th>Received (mBTC)</th>
        <th>BTC Price, $</th>
        <th>Payment Address</th>
      </tr>
    </thead>
    {% for registration_info in registration_infos %}
    <tr>
      <td>{{ registration_info.date_added|date:"m/d/Y" }}</td>
      <td>{{ registration_info.full_name }}</td>
      <td><a href="mailto:{{ registration_info.email_address }}">{{ registration_info.email_address }}</a></td>
      <td>{{ registration_info.get_payment_usd_str }}</td>
      <td>{{ registration_info.get_payment_mbtc_str }}</td>
      <td {% if registration_info.paid %}class="success"{% else %}class="warning"{% endif %}>{{ registration_info.get_received_mbtc_str }}</td>
      <td>{{ registration_info.get_btc_price_str }}</td>
      <td><a href="https://blockchain.info/address/{{ registration_info.btc_address }}" target="_blank">{{ registration_info.btc_address }}</a></td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
{% endblock %}